services:
  xampp:
    image: tomsik68/xampp:latest
    container_name: xampp
#    volumes:
#      - ./www:/www

    ports:
      - 41061:22
      - 8181:80 # apache server: phpmyadmin -> /dashboard
      - 3306:3306 # mariaDB server
    restart: unless-stopped
  flask-app:
    image: flask/app
    build: ./
    container_name: flask-app
    volumes:
      - ./app:/app
    ports:
      - 81:81
    restart: unless-stopped