services:
  flask-app:
    image: flask/app
    build: ./
    container_name: flask-app
    volumes:
      - ./app:/app
    ports:
      - 80:80
    restart: unless-stopped
  mariadb:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: liga
    ports:
    - "3306:3306"
    volumes:
    - "./liga.sql:/docker-entrypoint-initdb.d/liga.sql"