services:
  flask-app:
    image: flask/app
    build: ./
    container_name: flask-app
    volumes:
      - ./app:/app
    ports:
      - 81:81
    restart: unless-stopped
  mariadb:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: liga.sql
    ports:
    - "3306:3306"
    volumes:
    - "./liga.sql:/docker-entrypoint-initdb.d/1.sql"